_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 2
                - 5
            "12": 0.19.6
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_eps:
    value: 1e-08
attn_pdrop:
    value: 0.1
batch_size:
    value: 64
compile:
    value: false
context_length:
    value: 512
d_ff:
    value: 2048
d_model:
    value: 512
device:
    value: cuda
dtype:
    value: bfloat16
eval_interval:
    value: 500
grad_clip:
    value: 1
labels_csv:
    value: /home/shu4/koa_scratch/ECE491_Assignment2/data/positive_sample/labels.csv
learning_rate:
    value: 0.001
lr_scheduler:
    value: cosine
num_classes:
    value: 2
num_heads:
    value: 8
num_layers:
    value: 6
output_dir:
    value: /home/shu4/koa_scratch/ECE491_Assignment2/cs336-data/cs336_data/model
residual_pdrop:
    value: 0.1
train_steps:
    value: 100
vocab_size:
    value: 50000
wandb_project:
    value: TransformerTextClassification
warmup_ratio:
    value: 0.1
weight_decay:
    value: 0.01
